### ISSUE TITLE
RSDI 2018 Checklist

### ISSUE THREAD

**Issue by bridgethass** [bridgethass/NEON_RSDI#1]
**TO DO - RSDI 2018**

**Pre-Institute**
- [ ] Week 0: Update python installation instructions 
          - Use enviornment.yml file? Docker? JupyterHub?
          - Python 3.5
          - PySpTools (+ SpectralPy?)
          - Display python kernels in Jupyter notebook: run `conda install ipykernel` in that environment.
- [ ] Week 1: Intro to NEON - Megan
- [ ] Week 2: Intro to Python and Jupyter Notebooks
         - Data Types
         - Functions, For Loops, If Statements
         - Packages: numpy, matplotlib, gdal 
         - Optional: Linear Algebra and Introduction to Machine Learning - Coursera?
- [x] Lesson/tutorial (Jupyter Notebook) on reading in and plotting RGB camera tile 

**Day 1: Hyperspectral HDF5 Data**
- [ ] Update hyperspectral lessons to work with mosaiced tiles 
           - remove clipping to smaller extent
           - add batch processing of multiple tiles
- [ ] Update functions / module
         - Add functions to: 
              1. clean entire HSI cube (set no data value, scale, remove bad bands)
              2. Plot spectral signature of a pixel
              3. ...

**Day 2: Lidar Raster Data**

**Day 3: Remote Sensing Uncertainty**

**Day 4: Machine Learning with NEON Data - Classification, Clustering, and Applications**
- Spectral Python: http://www.spectralpython.net/user_guide.html
